#!/bin/bash

#script-generator

PKG=unipi-os-configurator-data

>"debian/${PKG}.postinst" cat <<EOF 
#!/bin/sh
set -e

EOF

>"debian/${PKG}.preinst" cat <<EOF 
#!/bin/sh
set -e

if ! [ -d /boot/overlays ]; then
    if [ -L /boot/overlays ]; then
        # lost symlink
        rm /boot/overlays
    fi
    if [ -d /boot/firmware ]; then
        ln -s /boot/firmware/overlays /boot/overlays
    elif [ -d /boot/loader ]; then
        ln -s /boot/loader/overlays /boot/overlays
    fi
fi

  mkdir -p /usr/share/rpikernelhack/overlays
EOF

for DTB in overlays/*.dtbo; do
>>"debian/${PKG}.postinst" cat <<EOF 
  if [ -f "/usr/share/rpikernelhack/${DTB}" ]; then
        rm -f "/boot/${DTB}"
        dpkg-divert --package rpikernelhack --remove --rename "/boot/${DTB}"
        sync
  fi
EOF

>>"debian/${PKG}.preinst" cat <<EOF 
  dpkg-divert --package rpikernelhack --rename --divert "/usr/share/rpikernelhack/${DTB}" "/boot/${DTB}"
EOF
done

>>"debian/${PKG}.postinst" cat <<EOF 

if [ "\$1" = "configure" ]; then
    if [ -x /opt/unipi/tools/os-configurator ]; then
        /opt/unipi/tools/os-configurator --force
    fi
fi

#DEBHELPER#
EOF

>>"debian/${PKG}.preinst" cat <<EOF 

#DEBHELPER#
EOF
